version: '3.8'

services:
  app:
    build: .
    container_name: c-learning-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
      - chatbot

  db:
    image: mysql:8.0
    container_name: c-learning-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./judge_questions.sql:/docker-entrypoint-initdb.d/judge_questions.sql
  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    container_name: c-learning-chatbot
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
volumes:
  db_data:
